version: '3'

services:
  db:
    image: postgres:14.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: always
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    command: gunicorn mirzade.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000

  nginx:
    image: nginx:1.21
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static_volume:/static
      - media_volume:/media
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    depends_on:
      - web
    restart: always

  # Yorumları otomatik çekmek için cron servisi
  cron:
    build: .
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    env_file:
      - ./.env
    depends_on:
      - web
    restart: always
    command: >
      sh -c "apt-get update && 
             apt-get install -y cron && 
             echo '0 3 * * * cd /code && python manage.py fetch_google_reviews --min-rating=4 >> /var/log/cron.log 2>&1' > /etc/cron.d/google-reviews && 
             chmod 0644 /etc/cron.d/google-reviews && 
             crontab /etc/cron.d/google-reviews && 
             touch /var/log/cron.log && 
             cron -f"

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  mirzade_network:
    driver: bridge 