# Generated by Django 5.1.6 on 2025-03-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tour_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='is_pet_friendly',
        ),
    ]
