# Generated by Django 5.1.6 on 2025-03-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_hotel_is_pet_friendly'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourreservation',
            name='total_persons',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Toplam Kişi Sayısı'),
        ),
        migrations.AddField(
            model_name='tourreservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Toplam Fiyat'),
        ),
    ]
