# Generated by Django 5.1.6 on 2025-03-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tourreservation_total_persons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourreservation',
            name='room_type',
            field=models.CharField(choices=[('double', 'İKİ KİŞİLİK ODA'), ('triple', 'ÜÇ KİŞİLİK ODA'), ('quad', 'DÖRT KİŞİLİK ODA')], default='double', max_length=20, verbose_name='Oda Tipi'),
        ),
    ]
