# Generated by Django 5.1.6 on 2025-03-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_tourreservation_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_luxury',
            field=models.BooleanField(default=False, verbose_name='Lüks Tur'),
        ),
        migrations.AddField(
            model_name='tour',
            name='luxury_amenities',
            field=models.TextField(blank=True, help_text='Her satıra bir hizmet yazın', null=True, verbose_name='Lüks Hizmetler'),
        ),
        migrations.AddField(
            model_name='tour',
            name='luxury_features',
            field=models.TextField(blank=True, help_text='Her satıra bir özellik yazın', null=True, verbose_name='Lüks Özellikler'),
        ),
        migrations.AddField(
            model_name='tour',
            name='special_guide',
            field=models.BooleanField(default=False, verbose_name='Özel Rehber'),
        ),
        migrations.AddField(
            model_name='tour',
            name='vip_transfer',
            field=models.BooleanField(default=False, verbose_name='VIP Transfer'),
        ),
    ]
