# Generated by Django 5.1.6 on 2025-03-22 12:43

import main.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tour_is_luxury_tour_luxury_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=main.models.OptimizedImageField(blank=True, null=True, upload_to='tour_images/', verbose_name='Tur Görseli'),
        ),
    ]
