# Generated by Django 5.1.6 on 2025-03-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourprogram',
            name='meals',
            field=models.CharField(blank=True, choices=[('breakfast', 'Kahvaltı'), ('lunch', 'Öğle Yemeği'), ('dinner', 'Akşam Yemeği'), ('breakfast_lunch', 'Kahvaltı ve Öğle Yemeği'), ('breakfast_dinner', 'Kahvaltı ve Akşam Yemeği'), ('lunch_dinner', 'Öğle ve Akşam Yemeği'), ('all_inclusive', 'Tüm Öğünler Dahil'), ('none', 'Yemek Dahil Değil')], default='breakfast', max_length=20, null=True, verbose_name='Yemekler'),
        ),
    ]
